# Site settings
title: cleartext
description: \#\#\#

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cleartext.sh" # the base hostname & protocol for your site

author:
  fullname: Vladimir Sofroniev
  github: vsofroniev
  twitter: vsofroniev
  linkedin: vladimirsofroniev

# google_analytics: 'UA-XXXXXXXX-X'
permalink: /archive/:title

# Handling Reading
exclude: ["README.md", "README.html"]

# Build settings
highlighter: null
markdown: kramdown
